#!/bin/bash

docker run -v ${TRAVIS_BUILD_DIR}:/tmp/installer -w /tmp/installer -it --rm $TARGET:$VERSION sh -c "\
      export DEBIAN_FRONTEND=noninteractive ; \
      apt-get update ; apt-get -y --no-install-recommends upgrade ; \
      apt-get install -y --no-install-recommends lsb-release git ca-certificates wget sudo ; \
      useradd -m -U pi ; \
      echo 'pi ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/010-pi ; \
      export TRIGGER_SOURCE=$TRIGGER_SOURCE ; \
      export TRIGGER_BRANCH=$TRIGGER_BRANCH ; \
      export HOME=/home/pi ; \
      sudo -EHu pi ./install-requirements.sh --system-install ; \
      sudo -EHu pi ./install-susi.sh --clean"

# was: sudo -E -u pi ./install.sh --use-sudo
