#!/bin/bash
set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
IFS=$'\n\t'
uname -r
ls

export LANG=C
export LC_ALL=C

apt-get update
apt-get upgrade -y --no-install-recommends
apt-get install -y --no-install-recommends git

sudo -u pi mkdir /home/pi/SUSI.AI
cd /home/pi/SUSI.AI && sudo -u pi git clone https://github.com/fossasia/susi_installer.git

# Run SUSI Linux's install script
cd /home/pi/SUSI.AI/susi_installer && git checkout development && sudo -Hu pi ./install.sh --clean

# After ./install.sh, the /dev is occupied by some processes and cannot be released by build script.
# We stop those processes to let the build script continue.

systemctl stop seeed-voicecard
systemctl stop systemd-udevd
sleep 5

#lsof +c0 /dev
#on_chroot << EOF
#systemcl stop systemd-udevd
#EOF
